<template>
  <div style="display: flex;justify-content: space-between">
    <HcVehicleSchema
      v-model:select-list="selectList"
      :axle-data="axleData"
      :spare-list="spareList"
      :tire-data="tireData"
      :unit="unit"
      :vehicle-data="vehicleData"
      :wheel-type="wheelType"
    />
    <Hc-Wheel-Schema :axleTypeList="axleTypeList" :spare-list="spareList" size="medium" style="margin-top: 50px" wheel-type="2-4-4" />

    <Hc-Wheel-Schema :axleTypeList="axleTypeList" :spare-list="spareList" size="small" style="margin-top: 50px" wheel-type="2-4-4" />

  </div>
<!--  <Hc-Wheel-Schema :spare-list="spareList" size="medium" style="margin-top: 50px" wheel-type="2-4-4" />-->

</template>

<script setup>
  import { ref } from 'vue'

  const wheelType = ref('2-4')
  const selectList = ref([])
  const tireData = {
    '2LO': {
      tire_no: '',
      id: 1329600,
      dot: '',
      rtd: '1',
      pressure: '2',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2LO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329600,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 1,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3LO': {
      tire_no: '',
      id: 1329600,
      dot: '',
      rtd: '3',
      pressure: '4',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3LO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329600,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 2,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '1L': {
      tire_no: '',
      id: 1329601,
      dot: '',
      rtd: '5',
      pressure: '6',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '1L',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: 1,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329601,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 2,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '1R': {
      tire_no: '',
      id: 1329602,
      dot: '',
      rtd: '6',
      pressure: '7',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '1R',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329602,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 4,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2LI': {
      tire_no: '',
      id: 1329603,
      dot: '',
      rtd: '',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2LI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329603,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: 1,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3LI': {
      tire_no: '',
      id: 1329603,
      dot: '3',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3LI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329603,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2RO': {
      tire_no: '',
      id: 1329604,
      dot: '3',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2RO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329604,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3RO': {
      tire_no: '',
      id: 1329604,
      dot: '2',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3RO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329604,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2RI': {
      tire_no: '',
      id: 1329605,
      dot: '',
      rtd: '3',
      pressure: '5',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2RI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329605,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3RI': {
      tire_no: '',
      id: 1329605,
      dot: '',
      rtd: '3',
      pressure: '2',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3RI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329605,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
  }
  const vehicleData = {
    id: 209573,
    customer_1: 200529,
    customer_2: 200530,
    customer_3: 200245,
    vehicle_no: 'A175877160062',
    car_number: '',
    vin: 'SGM1J45678',
    vehicletype_counter__type: 'Flat Bed Carrier',
    start_date: '2025-09-25T03:40:01.105577',
    operator: '200071',
    vehicle_status_id: 1,
    mileage: 300.0,
    remark: '2025-09-25 11:40:00',
    vehicleconfig_code__config_code: '464',
    vehicletype_counter__counter: '302',
    rfid_code: '',
    usage_time: null,
    make_id: null,
    model_id: null,
    last_inspection_id: 209715,
    activate_date: null,
    odometer_type: 'Hour',
    usage_type: null,
    fuel_type_code: null,
    total_mileage: 300.0,
    total_usage_time: null,
    edit_lock: false,
    contract_tire_ownership: null,
    vehicle_state: null,
    update_time: '2025-09-25T03:40:10.673700',
    fuel_type_name: '',
    usage_type_name: '',
    last_inspection_time: '2025-09-25 03:40:08',
    energy_type: 'Diesel',
    vehicle__vehicleconfig_code__configuration: 'S2.D4',
    inspection_type__name: '',
    vehicle__id: 209573,
    vehicle__vehicle_type: 'Flat Bed Carrier',
    vehicle_icon: 'https://ttmpeurope.fleetsguru.com/files/public/Flat-Bed-Carrier2.png?st=2025-09-25T05%3A07%3A38Z&se=2025-09-25T09%3A07%3A38Z&sp=r&sv=2021-06-08&ss=b&srt=o&sig=3IJKas2AqgRsynuVkKeWzHAT3aM/7qaaENJIfwZolFA%3D',
    wheel_type: '2-4',
    vehicle_wheel_config: 'S2.D4',
    vehicle_id: 209573,
    vehicle_status: 'Active',
    make_name: null,
    model_name: null,
    customer_1_name: 'Société Transport Express (STE)',
    customer_2_name: 'STE Puy de Dôme',
    customer_3_name: 'STE Aubière',
    pressure_unit: 'Bar',
    usage_time_unit: 'Day',
    mile_unit: 'km',
    rtd_unit: 'mm',
    followed: false,
    inspection_type_id: '',
    is_submmit: '',
    observation: '',
    observation_id_list: '',
    operation_types: '',
    no_today_mileage: null,
    no_today_mileage_date: null,
    no_today_usage_time: null,
    no_today_usage_time_date: null,
    vehicle_type_default_name: 'Flat Bed Carrier',
    name: 'Flat Bed Carrier',
    last_vehicle_log_time: '2025-09-25 03:40:10.672191',
  }
  const spareList = ref([
    { rtd: '1', pressure: '2', wheel_place: 'SP1' },
    { rtd: '', pressure: '', wheel_place: 'SP2' },
    { rtd: '1', pressure: '2', wheel_place: 'SP3', dismount: true },
  ])
  const unit = ref({
    pressure_unit: 'bar',
    rtd_unit: 'mm',
  })
  const axleTypeList = ref(['D2', 'S4','D2','S4'])
  const axleData = ref({
    0: {
      observationLevel: 0,
      recommendPressure: '8.8 bar',
      recommendSize: '315/80R22.5',
      type: 'D2',
    },
    1: {
      observationLevel: 1,
      recommendPressure: '8.8 bar',
      recommendSize: '315/80R22.5',
      type: 'S4',
    },
  })

</script>

<style scoped lang="less">

</style>
