<template>
  <div style="display: flex;justify-content: space-between">
    <HcVehicleSchema
      v-model:select-list="selectList"
      :axle-data="axleData"
      :spare-list="spareList"
      :tire-data="tireData"
      :unit="unit"
      :wheel-type="wheelType"
    />
    <Hc-Wheel-Schema :axle-type-list="axleTypeList" :spare-list="spareList" size="medium" style="margin-top: 50px" wheel-type="2-4-4" />

    <Hc-Wheel-Schema :axle-type-list="axleTypeList" :spare-list="spareList" size="small" style="margin-top: 50px" wheel-type="2-4-4" />

  </div>
<!--  <Hc-Wheel-Schema :spare-list="spareList" size="medium" style="margin-top: 50px" wheel-type="2-4-4" />-->

</template>

<script setup>
  import { ref } from 'vue'

  const wheelType = ref('2-4-4')
  const selectList = ref([])
  const tireData = {
    '1L': {
      tire_no: '',
      id: 1329601,
      dot: '',
      rtd: '',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '1L',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: 1,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329601,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '1R': {
      tire_no: '',
      id: 1329602,
      dot: '',
      rtd: '6',
      pressure: '7',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '1R',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329602,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2LO': {
      tire_no: '',
      id: 1329600,
      dot: '',
      rtd: '1',
      pressure: '2',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2LO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329600,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 1,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2LI': {
      tire_no: '',
      id: 1329603,
      dot: '',
      rtd: '',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2LI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329603,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: 1,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2RI': {
      tire_no: '',
      id: 1329605,
      dot: '',
      rtd: '3',
      pressure: '5',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2RI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329605,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '2RO': {
      tire_no: '',
      id: 1329604,
      dot: '3',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '2RO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329604,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3LO': {
      tire_no: '',
      id: 1329600,
      dot: '',
      rtd: '3',
      pressure: '4',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3LO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329600,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 0,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3LI': {
      tire_no: '',
      id: 1329603,
      dot: '3',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3LI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329603,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 1,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3RI': {
      tire_no: '',
      id: 1329605,
      dot: '',
      rtd: '3',
      pressure: '2',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3RI',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329605,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 2,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
    '3RO': {
      tire_no: '',
      id: 1329604,
      dot: '2',
      rtd: '5',
      pressure: '',
      vehicle__vehicle_no: 'A175877160062',
      wheel_place: '3RO',
      CAI: null,
      CAI__name: '',
      CAI__CAI: '',
      CAI__otd: null,
      CAI__season: null,
      rfid_code: null,
      is_virtual: 1,
      remark: null,
      is_regroove: null,
      regroove_times: 0,
      barcode: null,
      owner_type: null,
      temp_cai_id: null,
      tire_id: 1329604,
      belonging: null,
      repair_status: 'Non-repaired',
      accumulating_repair_time: 0,
      lock_status: false,
      is_retread: null,
      customer_1_id: 200529,
      observation: [],
      observation_level: 3,
      rtd_observation_level: 0,
      pressure_observation_level: 0,
      inspected: false,
      rtds: '',
      is_temp_cai: false,
      otd: null,
      MSPN: '',
      CAI_name: '',
      spec: '',
      brand: '',
      pattern: '',
      pic: [],
      is_bind_rfid: false,
      target_pressure: 10.0,
      recommend_size: '',
      rtd_list: '',
      rtd_warning: false,
      pressure_warning: false,
      tire_life: '',
      season: null,
    },
  }

  const spareList = ref([
    { rtd: '1', pressure: '2', wheel_place: 'SP1' },
    { rtd: '', pressure: '', wheel_place: 'SP2' },
    { rtd: '1', pressure: '2', wheel_place: 'SP3', dismount: true },
    { rtd: '1', pressure: '2', wheel_place: 'SP4', dismount: true },
    { rtd: '1', pressure: '2', wheel_place: 'SP5' },
  ])
  const unit = ref({
    pressure_unit: 'bar',
    rtd_unit: 'mm',
  })
  const axleTypeList = ref(['D2', 'S4', 'S4'])
  const axleData = ref({
    0: {
      observationLevel: 0,
      recommendPressure: '8.8 bar',
      recommendSize: '315/80R22.5',
      type: 'D2',
    },
    1: {
      observationLevel: 2,
      recommendPressure: '8.8 bar',
      recommendSize: '315/80R22.5',
      type: 'S4',
    },
    2: {
      observationLevel: 3,
      recommendPressure: '8.8 bar',
      recommendSize: '315/80R22.5',
      type: 'S4',
    },
  })

</script>

<style scoped lang="less">

</style>
